# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YGShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YGShop
  pod 'AFNetworking'
  pod 'Masonry'

  target 'YGShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YGShopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
